name: Update README with List of files in directory
on:
  workflow_dispatch: # triggers manually
  schedule:
  - cron: "0 0 * * *" # triggers every midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run List of files by extension action
      uses: alisuleymantopuz/list-of-files-by-extension-github-action@main
    - name: Commit and push update
      run: |-
        git commit -m "Added List of files by extension from GitHub Actions"
        git push
